#!/usr/bin/env zsh
# ============================================================
#  .zshrc — WSL-native (no platform conditionals)
#  Repo: https://github.com/smnuman/config-zsh
#  Generated by init-convert.sh; all platform decisions
#  baked in at generation time.
# ============================================================

autoload -Uz add-zsh-hook

[[ -f "$ZDOTDIR/env.zsh" ]] && source "$ZDOTDIR/env.zsh"

# === Phase 3: WSL Environment Files ===
zsh_bootlog "Phase 3: loading WSL environment"
for f in "$ZDOTDIR"/env/[0-9][0-9][0-9]-*.zsh(N); do
  source "$f"
done
[[ -f "$ZUTILS/wsl.zsh" ]] && source "$ZUTILS/wsl.zsh"

zsh_bootlog "Phase 4: loading zsh options"
zprof_start "options"

# === Zsh Options ===
[[ -f "$ZDOTDIR/zsh-optionrc" ]] && source "$ZDOTDIR/zsh-optionrc"

zprof_end "options"

zsh_bootlog "Phase 5: loading key bindings"
zprof_start "keybinds"

# === Key Bindings ===
[[ -f "$ZDOTDIR/lib/keybinds.zsh" ]] && source "$ZDOTDIR/lib/keybinds.zsh"

zprof_end "keybinds"

zsh_bootlog "Phase 6: configuring git (async)"

# === Git Init (async — non-blocking) ===
{
  zsh_bootlog "Phase 6: git init started"
  [[ ! -f ~/.gitconfig ]] && ln -s ~/.config/git/gitconfig ~/.gitconfig 2>/dev/null
  [[ -f "$ZDOTDIR/lib/zsh-initgit.zsh" ]] && source "$ZDOTDIR/lib/zsh-initgit.zsh"
} >> "$ZLOGDIR/boot_async_git.zlog" 2>&1 &!
#  --- git utilities ---
[[ -f "$ZDOTDIR/git-utils/git_users.zsh" ]] && source "$ZDOTDIR/git-utils/git_users.zsh"
#  --- secrets (git-crypt encrypted) ---
[[ -f "$ZDOTDIR/secrets.key" ]] && source "$ZDOTDIR/secrets.key" 2>/dev/null
#  --- git workflow ---
[[ -f "$ZDOTDIR/git-utils/gw.zsh" ]] && source "$ZDOTDIR/git-utils/gw.zsh"

zsh_bootlog "Phase 7: loading plugin manager"
zprof_start "plugins"

# === Plugin Manager ===
[[ -f "$ZDOTDIR/lib/plugin_manager.zsh" ]] && source "$ZDOTDIR/lib/plugin_manager.zsh"

zprof_end "plugins"

zsh_bootlog "Phase 8: loading modules"
zprof_start "modules"

# === Module Loader (aliases, exports, functions, completions) ===
[[ -f "$ZDOTDIR/lib/zsh-init.zsh" ]] && source "$ZDOTDIR/lib/zsh-init.zsh"

# # Buil-in Prompt themes
# autoload -Uz promptinit && promptinit 
# prompt bart 

zprof_end "modules"

zsh_bootlog "Phase 9: loading fuzzy tools"
zprof_start "fuzzy"

# === Fuzzy Tools (fzf + zoxide) ===
[[ -f "$ZDOTDIR/lib/zsh-fuzzy.zsh" ]] && source "$ZDOTDIR/lib/zsh-fuzzy.zsh"

zprof_end "fuzzy"

# zsh_bootlog "Phase 10: loading prompt"
# zprof_start "prompt"

# # === Prompt ===
# PROMPT_SHOWN="false"
# export PROMPT_SHOWN
# precmd() { PROMPT_SHOWN="true" }

# fpath=("$ZDOTDIR/lib/prompts" "$ZDOTDIR/prompt" $fpath)
# autoload -Uz promptinit && promptinit 2>/dev/null
# [[ -f "$ZDOTDIR/zsh-prompt" ]] && source "$ZDOTDIR/zsh-prompt"

# zprof_end "prompt"

zsh_bootlog "Phase 10: loading completions"
zprof_start "completions"

# === Completions ===
[[ -f "$ZDOTDIR/completions.zsh" ]] && source "$ZDOTDIR/completions.zsh"

zprof_end "completions"

# === Phase 11: history-toggle + local overrides ===
zsh_bootlog "Phase 11: history-toggle + local overrides"
zprof_start "overrides"

# === history-toggle (shared/private history mode) ===
[[ -f "$ZUTILS/history-toggle" ]] && source "$ZUTILS/history-toggle"

# === claude-mem-quiet (verbose/quiet session-start context) ===
[[ -f "$ZUTILS/claude-mem-quiet" ]] && source "$ZUTILS/claude-mem-quiet"

# === Local overrides (gitignored) ===
[[ -f "$ZDOTDIR/.zshrc.local" ]] && source "$ZDOTDIR/.zshrc.local"

zprof_end "overrides"

zsh_bootlog "Phase 12: .zshrc complete."

zprof_end "TOTAL"

# === Profile dump ===
zprof_report

# OpenClaw Completion (portable: repo-shipped, guarded — was hardcoded /home/numan/...)
[[ -f "$ZDOTDIR/completions/openclaw.zsh" ]] && source "$ZDOTDIR/completions/openclaw.zsh"
