#!/usr/bin/env zsh
# Setup the basic environment
export TERM="xterm-256color"    # Use 256 colors in terminal
export EDITOR="vim"             # Set default editor to Neovim
export VISUAL="$EDITOR"         # Set visual editor to Neovim
export BAT_THEME='gruvbox-dark' # Set bat theme to gruvbox-dark

export CLICOLOR=1
export LSCOLORS='GxHgExDxCxhbadabaggacad'  # Custom ls colors for Mac OS
export GREP_OPTIONS='--color=auto'
export K_SHOW_GIT=1             # for 'k' to work with git status
# lsg: ls-with-git-status from:https://github.com/gerph/ls-with-git-status/
export LSG_COMMAND=             # use 'gls' on Mac OS to force the GNU version.(default: 'ls')
export LSG_OPTIONS=' -alGgo'

# For compilers to find curl you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"

export HOMEBREW_INSTALL_BADGE="☕️ 🐸"
export HOMEBREW_INSTALL_BADGE_COLOR="green"

export ZSH_HISTORY_SEARCH_STYLE="bashlike"  # Cursor at end (default), or use "zshlike"

export_path "$BREWDOTS"
export_path "$ZUTILS"
export_path "$BRUTILS"
export_path "$ZDOTDIR/git-utils/"
export_path "$XDG_CONFIG_HOME/tmux/scripts/"
export_path "$XDG_CONFIG_HOME/tmux/plugins/tpm/bin/"

export NNN_OPTS='eEx'
export NNN_PLUG='p:preview-tui;o:fzopen'
