#!/usr/bin/env zsh
# completion list keybindings and settings
# ~/.config/zsh/zsh-complist

# --- History Search Keybindings ---
autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search        # Ctrl+P: search history backward (up)
bindkey '^[[B' down-line-or-beginning-search      # Ctrl+N: search history forward (down)
bindkey '^R' history-incremental-search-backward    # Use Ctrl+R to search history
#  if below is present, must add `stty -ixon` to .zshrc before 
# bindkey '^S' history-incremental-search-forward     # Use Ctrl+S to search history forward (if terminal supports it)


# --- Completion Menu Configuration ---
zmodload -i zsh/complist                        # Load completion list module quietly
zstyle ':completion:*' menu select=1            # Start menu selection after first match
zstyle ':completion:*' completer _complete _ignored _approximate _correct _menu_select  # Define completers§
zstyle ':completion:*' single-ignored show-ignored  # Show ignored files in completions
_comp_options+=(globdots)                       # Include dotfiles in completions

# Completion sorting and grouping
zstyle ':completion:*'              sort true
zstyle ':completion:*'              list-suffixes true
zstyle ':completion:*'              group-name ''
zstyle ':completion:*'              matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*:default'      list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*'              ignored-patterns '*~' '*.o' '*.pyc' '*.bak' '*.backup' '*.archive' '*.arc?'  # Ignore backup/archive files
zstyle ':completion:*'              file-patterns '*(-/):directories' '*(N)'
zstyle ':completion:*'              verbose yes
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*'              use-cache on
[[ -d "$ZDOTDIR/.zcompcache" ]] || mkdir -p "$ZDOTDIR/.zcompcache"
zstyle ':completion:*'              cache-path "$ZDOTDIR/.zcompcache"
zstyle ':completion:*'              expand 'yes'

zstyle ':fzf-tab:complete:cd:*'             fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*'     fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:*' fzf-preview 'eza --tree $realpath 2>/dev/null || ls -la $realpath'

