#!/usr/bin/env zsh

ZPROMPT_DIR="$ZDOTDIR/prompt"

PROMPT_DEFAULTS="$ZPROMPT_DIR/prompt-defaults"
PROMPT_RC="${XDG_CONFIG_HOME:-$HOME/.config}/.promptrc"
PROMPT_UTILS="$ZPROMPT_DIR/prompt-utils.zsh"
PROMPT_INIT="$ZPROMPT_DIR/prompt-init.zsh"
PROMPT_GIT_STAT="$ZPROMPT_DIR/prompt-git-status.zsh"

if [[ -f $PROMPT_UTILS && -f $PROMPT_INIT && -f $PROMPT_GIT_STAT ]]; then
    source $PROMPT_GIT_STAT  
    [[ -f $PROMPT_RC ]] && source $PROMPT_RC || echo "zsh-prompt: warning: .promptrc not found"            # user overrides via ~/.config/.promptrc
    source $PROMPT_DEFAULTS 
    source $PROMPT_UTILS
    source $PROMPT_INIT
    print -P "%F{green}zsh-prompt loaded successfully%f"
else
    export PS1="[ %T ] %~ %# "
fi
